#! /bin/bash
#
# chkconfig: 2345 93 11
#
# description:nginx
#
# set_env_path
#
#
#
# Program_name
#
	NAME="nginx"
#
# Program_install_dir
#
	program_install_dir_prefix="/usr/jiangwu/"$NAME
#
#
# execute_file
	execute=$program_install_dir_prefix/sbin/nginx
#
# pid_file
    pid="/usr/jiangwu/nginx/logs/nginx.pid"
#


check(){

	if [-f $pid]
	then
		ps aux | grep $(cat $pid) | wc -l
	else
		echo -e "\033[31m$NAME 找不到pid文件 \033[0m"
	fi
}
	
start() {
	isRun=`check`
	if [ 0 -lt $isRun ]
	then

		echo -e "\033[32m$NAME正在运行 \033[0m"
	else
	
		echo "尝试启动"$NAME
		$execute
		sleep 1
		isRun=`check`
		if [ 0 -lt $isRun ]
		then
			echo -e "\033[32m$NAME启动成功 \033[0m"
		else
				
			echo -e "\033[31m$NAME启动失败 \033[0m"
		fi
	fi
}

stop() {
	isRun=`check`
	
	if [ 0 -lt $isRun ]
	then
		echo -e "\033[32m尝试停止$NAME... \033[0m"
		#$execute stop
		kill -15 $(cat $pid) 
		sleep 1
		isRun=`check`
		if [ 0 -eq $isRun ]
		then
			echo -e "\033[32m停止成功 \033[0m"
		else
			echo -e "\033[31m$NAME停止失败 \033[0m"
		fi
	else
		echo -e "\033[31m$NAME未运行 \033[0m"
	fi
}

#
#reload_config_file

reload(){
	$execute -s reload
}
status() {
	isRun=`check`
	if [ 0 -lt $isRun ]
	then
		
		echo -e "\033[32m$NAME正在运行 \033[0m"
	else
		echo $NAME"未运行"
	fi
}
case "$1" in  
  start)  
        start  
        ;;  
  stop)  
        stop  
        ;;
  status)
	status
	;;  
  restart)           
       stop
	   sleep 1
       start  
        ;;
  reload)
	reload
	  ;;
   *)  
        echo "参数错误!"  
        echo $"Usage: $0 {start|stop|status|restart|reload}"  
        exit 1  
        ;;  
esac  
exit $RETVAL  
