#! /bin/bash
#
# chkconfig: 2345 93 11
#
# description:php-fpm
#
# set_env_path
#
#
#
# Program_name
#
	NAME="php-fpm"
#
# Program_install_dir
#
	program_install_dir_prefix="/usr/local/php"
#
#
# execute_file
	execute=$program_install_dir_prefix/sbin/php-fpm
#
# pid_file
    pid="/usr/local/php/var/run/php-fpm.pid"
#


check(){

	if [ -f $pid ]
	then
		ps aux | grep $(cat $pid) |grep -v grep | wc -l
	else
		echo 0
	fi
}
	
start() {
	isRun=`check`
	if [ 0 -lt "$isRun" ]
	then

		echo -e "\033[32m$NAME正在运行 \033[0m"
	else
	
		echo "尝试启动"$NAME
		$execute
		sleep 1
		isRun=`check`
		if [ 0 -lt "$isRun" ]
		then
			echo -e "\033[32m$NAME启动成功 \033[0m"
		else
				
			echo -e "\033[31m$NAME启动失败 \033[0m"
		fi
	fi
}

stop() {
	isRun=`check`
	
	if [ 0 -lt "$isRun" ]
	then
		echo -e "\033[32m尝试停止$NAME... \033[0m"
		#$execute stop
		kill -15 $(cat $pid) 
		sleep 1
		isRun=`check`
		if [ 0 -eq "$isRun" ]
		then
			echo -e "\033[32m停止成功 \033[0m"
		else
			echo -e "\033[31m$NAME停止失败 \033[0m"
		fi
	else
		echo -e "\033[31$NAME未运行 \033[0m"
	fi
}

status() {
	isRun=`check`
	if [ 0 -lt "$isRun" ]
	then
		
		echo -e "\033[32m$NAME正在运行 \033[0m"
	else
		echo $NAME"未运行"
	fi
}
case "$1" in  
  start)  
        start  
        ;;  
  stop)  
        stop  
        ;;
  status)
	status
	;;  
  restart)           
       stop
	   sleep 1
       start  
        ;;  
   *)  
        echo "参数错误!"  
        echo $"Usage: $0 {start|stop|status|restart}"  
        exit 1  
        ;;  
esac  
exit $RETVAL  
